name: CI - Build & Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: lanceacrdev2025.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t lanceacrdev2025.azurecr.io/my-dotnet-app:v1 ./app/MyDotNetApp

      - name: Push Docker image to ACR
        run: |
          docker push lanceacrdev2025.azurecr.io/my-dotnet-app:v1

